var sweety="Sweety";
var cutie="Cutie";
var temp;
console.log("value before swap:-"+"sweety:"+sweety+"  " +"and"+"  "+"cutie:"+cutie);
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("value after swap:-"+"sweety:"+sweety+"  " +"and"+"  "+"cutie:"+cutie);
var num1=100;
var num2=200;
var num3=300;
var temp;
console.log("value before swap:-"+"num1:"+num1+" ,"+"num2:"+num2+" , "+"num3:"+num3);
temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("value after swap:-"+"num1:"+num1+" ,"+"num2:"+num2+" , "+"num3:"+num3);